global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: machina-api
    static_configs:
      - targets: ["api:8000"]
    metrics_path: /metrics

  - job_name: machina-processor
    static_configs:
      - targets: ["processor:9101"]
    metrics_path: /metrics
